spring:
  application:
    name: "CashMan"
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:cashman;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2

cashman-util:
  inventory-scan:
    denomination-threshold: 5
    frequency.ms: 60000
    initial.delay.ms: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html